<a href="https://colab.research.google.com/github/rohitkuma6443/Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction to Pandas

Pandas is built on top of the NumPy library, providing high-performance, easy-to-use data structures and data analysis tools. It's particularly well-suited for tabular data, similar to spreadsheets or SQL tables.

### Role in Data Analysis

Pandas is a cornerstone of the data science ecosystem in Python. It excels at:
*   **Data Cleaning:** Handling missing data, removing duplicates, and correcting inconsistencies.
*   **Data Transformation:** Reshaping, merging, and aggregating datasets.
*   **Data Exploration:** Providing intuitive methods to inspect and summarize data.

### Installation and Setup

In environments like Google Colab, Pandas is usually pre-installed. If you were working in a local environment, you would typically install it using pip:
`pip install pandas`

### Importing Pandas

The standard convention for importing Pandas is to use the alias `pd`.

In [5]:
import pandas as pd

print(f"Pandas version: {pd.__version__}")

# Pandas relies on NumPy for its underlying numerical operations
import numpy as np

print(f"NumPy version: {np.__version__}")

Pandas version: 2.2.2
NumPy version: 2.0.2

## Module 2: Core Data Structures

Pandas introduces two primary data structures: `Series` and `DataFrame`. Understanding these is crucial, as they are the foundation for almost all operations in Pandas.

### Pandas Series

A `Series` is a one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc.). It's similar to a column in a spreadsheet or a SQL table, or a NumPy array with an associated index (labels).

**Creation of a Series:**

You can create a Series from a list, NumPy array, or dictionary.

In [101]:
# Create a Series from a list
data_list = [10, 20, 30, 40, 50]

data_series = pd.Series(data_list)
print("Series from a list:")
display(data_series)

# Create a Series with a custom index
data_list_custom = ['apple', 'banana', 'cherry']
custom_index = ['a', 'b', 'c']
s2 = pd.Series(data_list_custom, index=custom_index)
print("\nSeries with custom index:")
display(s2)

# Create a Series from a dictionary
data_dict = {'A': 100, 'B': 200, 'C': 300}
s3 = pd.Series(data_dict)
print("\nSeries from a dictionary:")
display(s3)

Series from a list:

0    10
1    20
2    30
3    40
4    50
dtype: int64

Series with custom index:

a     apple
b    banana
c    cherry
dtype: object

Series from a dictionary:

A    100
B    200
C    300
dtype: int64

### Pandas DataFrame

A `DataFrame` is a two-dimensional labeled data structure with columns of potentially different types. It is like a spreadsheet, SQL table, or a dictionary of Series objects. It is the most commonly used Pandas object.

**Creation of a DataFrame:**

You can create a DataFrame from dictionaries, lists of dictionaries, or even other DataFrames.

In [7]:
# Create a DataFrame from a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
data_frame = pd.DataFrame(data)
print("DataFrame from a dictionary of lists:")
display(data_frame)

# Create a DataFrame from a list of dictionaries
data_list_dict = [
    {'Name': 'Eve', 'Age': 28, 'City': 'Miami'},
    {'Name': 'Frank', 'Age': 32, 'City': 'Boston'}
]
df_from_list_dict = pd.DataFrame(data_list_dict)
print("\nDataFrame from a list of dictionaries:")
display(df_from_list_dict)

DataFrame from a dictionary of lists:

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

DataFrame from a list of dictionaries:

    Name  Age    City
0    Eve   28   Miami
1  Frank   32  Boston

### Data Types (dtypes)

Pandas automatically infers data types for Series and DataFrame columns. Common data types include:

*   `int64`: Integer numbers
*   `float64`: Floating-point numbers
*   `object`: Strings or mixed types
*   `bool`: Boolean (True/False)
*   `datetime64`: Date and time values
*   `category`: Categorical values (useful for efficiency and specific operations)

You can inspect the data types using the `.dtype` (for Series) or `.dtypes` (for DataFrame) attributes.

### Index and MultiIndex

Every Series and DataFrame has an `Index`, which provides labels for rows (and columns in the case of a DataFrame).

**Index:**

The index can be a simple range of numbers (default), or custom labels (strings, dates, etc.).

In [96]:
import numpy as np

data_missing = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [10, 20, 30, np.nan, 50]
}
df_missing = pd.DataFrame(data_missing)
print("Original DataFrame with missing values:")
display(df_missing)

# Drop rows with any missing values
df_dropped_rows = df_missing.dropna()
print("DataFrame after dropping rows with any NaN:")
display(df_dropped_rows)

# Drop columns with any missing values
df_dropped_cols = df_missing.dropna(axis=1)
print("\nDataFrame after dropping columns with any NaN:")
display(df_dropped_cols)

Original DataFrame with missing values:

     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  NaN  3.0  30.0
3  4.0  4.0   NaN
4  5.0  NaN  50.0

DataFrame after dropping rows with any NaN:

     A    B     C
1  2.0  2.0  20.0

DataFrame after dropping columns with any NaN:

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

**MultiIndex (Hierarchical Indexing):**

MultiIndex is an advanced feature that allows for multiple levels of indexing on an axis. This is very powerful for working with higher-dimensional data in a 2D structure.

You can create a MultiIndex from a list of arrays or tuples.

In [100]:
# Fill with a constant value (e.g., 0)
df_filled_zero = df_missing.fillna(0)
print("DataFrame after filling NaN with 0:")
display(df_filled_zero)

# Fill with the mean of each column
df_filled_mean = df_missing.fillna(df_missing.mean())
print("\nDataFrame after filling NaN with column means:")
display(df_filled_mean)

DataFrame after filling NaN with 0:

     A    B     C
0  1.0  0.0  10.0
1  2.0  2.0  20.0
2  0.0  3.0  30.0
3  4.0  4.0   0.0
4  5.0  0.0  50.0

DataFrame after filling NaN with column means:

     A    B     C
0  1.0  3.0  10.0
1  2.0  2.0  20.0
2  3.0  3.0  30.0
3  4.0  4.0  27.5
4  5.0  3.0  50.0

In [95]:
print("DataFrame.isnull():")
display(df_missing.isnull())

print("\nSum of missing values per column:")
display(df_missing.isnull().sum())

print("\nTotal number of missing values:")
display(df_missing.isnull().sum().sum())

DataFrame.isnull():

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True
4  False   True  False

Sum of missing values per column:

A    1
B    2
C    1
dtype: int64

Total number of missing values:

np.int64(4)

## Module 3: Data Input / Output (I/O)

One of Pandas' most crucial features is its ability to read data from and write data to various file formats. This module will cover the most common input/output operations, which are essential for any data analysis workflow.

### Reading Files

Pandas provides a suite of functions to read data from different sources. The most frequently used are `read_csv()`, `read_excel()`, and `read_json()`.

**`pd.read_csv()`: Reading from CSV files**

This is perhaps the most common function for loading tabular data. It's highly flexible and can handle various delimiters, headers, and encoding options.

In [ ]:
# Create a DataFrame for group-wise filling
df_with_na = pd.DataFrame({
    'Group': ['A', 'A', 'B', 'B', 'A'],
    'Value': [10, np.nan, 20, np.nan, 15]
})
print("Original DataFrame for group-wise filling:")
display(df_with_na)

# Fill NaN values with the mean of their respective groups
df_with_na['Value_Filled_Group_Mean'] = df_with_na.groupby('Group')['Value'].transform(lambda x: x.fillna(x.mean()))
print("\nDataFrame after filling NaN with group-wise mean:")
display(df_with_na)

**`pd.read_json()`: Reading from JSON files**

JSON (JavaScript Object Notation) is another popular format, especially for web-based data. Pandas can directly read JSON strings or files.

In [9]:
data_duplicates = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'City': ['NY', 'LA', 'NY', 'CHI', 'LA']
}
df_duplicates = pd.DataFrame(data_duplicates)
print("Original DataFrame with duplicates:")
display(df_duplicates)

Original DataFrame with duplicates:

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
2    Alice   25   NY
3  Charlie   35  CHI
4      Bob   30   LA

### Writing Files

Just as easily as reading, Pandas allows you to export your DataFrames back into various file formats using methods like `to_csv()`, `to_excel()`, and `to_json()`.

**`df.to_csv()`: Writing to CSV files**

This method writes the DataFrame to a CSV file. You can control whether to include the index, header, and other formatting options.

In [10]:
print("Boolean Series indicating duplicated rows:")
display(df_duplicates.duplicated())

print("\nDuplicated rows themselves (keeping the first occurrence):")
display(df_duplicates[df_duplicates.duplicated()])

Boolean Series indicating duplicated rows:

0    False
1    False
2     True
3    False
4     True
dtype: bool

Duplicated rows themselves (keeping the first occurrence):

    Name  Age City
2  Alice   25   NY
4    Bob   30   LA

### Working with Large Datasets using `chunksize`

For very large files that don't fit into memory, Pandas' `read_csv()` and `read_json()` functions offer a `chunksize` parameter. This allows you to read the file in smaller, manageable chunks, process each chunk, and then combine or aggregate the results.

This approach is essential for memory-efficient processing of big data.

In [11]:
# Remove all duplicate rows (keeps the first occurrence by default)
df_no_duplicates = df_duplicates.drop_duplicates()
print("DataFrame after dropping all duplicate rows:")
display(df_no_duplicates)

# Remove duplicates based on a subset of columns (e.g., 'Name' and 'Age')
df_no_duplicates_subset = df_duplicates.drop_duplicates(subset=['Name', 'Age'])
print("\nDataFrame after dropping duplicates based on 'Name' and 'Age':")
display(df_no_duplicates_subset)

# Keep the last occurrence of duplicates instead of the first
df_no_duplicates_last = df_duplicates.drop_duplicates(keep='last')
print("\nDataFrame after dropping duplicates, keeping the last occurrence:")
display(df_no_duplicates_last)

DataFrame after dropping all duplicate rows:

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   35  CHI

DataFrame after dropping duplicates based on 'Name' and 'Age':

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   35  CHI

DataFrame after dropping duplicates, keeping the last occurrence:

      Name  Age City
2    Alice   25   NY
3  Charlie   35  CHI
4      Bob   30   LA

In [12]:
# Create a dummy CSV file for demonstration
data_csv = """Name,Age,City
Alice,25,New York
Bob,30,Los Angeles
Charlie,35,Chicago"""

with open('sample.csv', 'w') as f:
    f.write(data_csv)

# Read a CSV file
df_csv = pd.read_csv('sample.csv')
print("DataFrame from CSV:")
display(df_csv)

DataFrame from CSV:

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Module 3: Data Input / Output (I/O)

One of Pandas' most crucial features is its ability to read data from and write data to various file formats. This module will cover the most common input/output operations, which are essential for any data analysis workflow.

### Reading Files

Pandas provides a suite of functions to read data from different sources. The most frequently used are `read_csv()`, `read_excel()`, and `read_json()`.

**`pd.read_csv()`: Reading from CSV files**

This is perhaps the most common function for loading tabular data. It's highly flexible and can handle various delimiters, headers, and encoding options.

In [13]:
# Convert 'Age' column from int64 to float64
df_age_float = data_frame['Age'].astype(float)
print("Original 'Age' dtype:", data_frame['Age'].dtype)
print("Converted 'Age' Series dtype:", df_age_float.dtype)
display(df_age_float)

# Convert back to int64 (will error if NaNs are present)
# df_age_int = df_age_float.astype(int) # This would work if no NaNs were introduced

# Example with a DataFrame column
df_copy = data_frame.copy()
df_copy['Age'] = df_copy['Age'].astype('float32')
print("\nDataFrame 'Age' column converted to float32:")
display(df_copy.dtypes)

Original 'Age' dtype: int64
Converted 'Age' Series dtype: float64

0    25.0
1    30.0
2    35.0
3    40.0
Name: Age, dtype: float64

DataFrame 'Age' column converted to float32:

Name     object
Age     float32
City     object
dtype: object

**`pd.read_json()`: Reading from JSON files**

JSON (JavaScript Object Notation) is another popular format, especially for web-based data. Pandas can directly read JSON strings or files.

In [14]:
# Create a Series with mixed types (string and int)
string_numbers = pd.Series(['10', '20', '30', '40'])
df_str_num = pd.DataFrame({'Value': string_numbers})
print("Original Series with string numbers:")
display(df_str_num)
print("Original dtype:", df_str_num['Value'].dtype)

# Convert to numeric, coercing errors
df_str_num['Value'] = pd.to_numeric(df_str_num['Value'], errors='coerce')
print("\nSeries after pd.to_numeric with errors='coerce':")
display(df_str_num)
print("New dtype:", df_str_num['Value'].dtype)

Original Series with string numbers:

  Value
0    10
1    20
2    30
3    40

Original dtype: object

Series after pd.to_numeric with errors='coerce':

   Value
0     10
1     20
2     30
3     40

New dtype: int64

### Writing Files

Just as easily as reading, Pandas allows you to export your DataFrames back into various file formats using methods like `to_csv()`, `to_excel()`, and `to_json()`.

**`df.to_csv()`: Writing to CSV files**

This method writes the DataFrame to a CSV file. You can control whether to include the index, header, and other formatting options.

In [15]:
data_dt = {
    'OrderID': [1, 2, 3, 4, 5],
    'Customer': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'OrderDate': ['2023-01-15', '2023-01-16', '2023-02-01', '2023-02-02', '2023-03-10'],
    'Amount': [100.50, 75.25, 200.00, 50.00, 120.75]
}
df_datetime_sample = pd.DataFrame(data_dt)

print("Original DataFrame with 'OrderDate' as object dtype:")
display(df_datetime_sample.info())

# Convert 'OrderDate' to datetime objects
df_datetime_sample['OrderDate'] = pd.to_datetime(df_datetime_sample['OrderDate'])

print("\nDataFrame after converting 'OrderDate' to datetime dtype:")
display(df_datetime_sample.info())
display(df_datetime_sample.head())

Original DataFrame with 'OrderDate' as object dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      object
 3   Amount     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

None

DataFrame after converting 'OrderDate' to datetime dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      datetime64[ns]
 3   Amount     5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 292.0+ bytes

None

   OrderID Customer  OrderDate  Amount
0        1    Alice 2023-01-15  100.50
1        2      Bob 2023-01-16   75.25
2        3  Charlie 2023-02-01  200.00
3        4    David 2023-02-02   50.00
4        5      Eve 2023-03-10  120.75

### Working with Large Datasets using `chunksize`

For very large files that don't fit into memory, Pandas' `read_csv()` and `read_json()` functions offer a `chunksize` parameter. This allows you to read the file in smaller, manageable chunks, process each chunk, and then combine or aggregate the results.

This approach is essential for memory-efficient processing of big data.

In [16]:
df_cat = data_frame.copy()
df_cat['City'] = df_cat['City'].astype('category')

print("Original 'City' dtype:", data_frame['City'].dtype)
print("Converted 'City' dtype:", df_cat['City'].dtype)
display(df_cat.head())

Original 'City' dtype: object
Converted 'City' dtype: category

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## Module 3: Data Input / Output (I/O)

One of Pandas' most crucial features is its ability to read data from and write data to various file formats. This module will cover the most common input/output operations, which are essential for any data analysis workflow.

### Reading Files

Pandas provides a suite of functions to read data from different sources. The most frequently used are `read_csv()`, `read_excel()`, and `read_json()`.

**`pd.read_csv()`: Reading from CSV files**

This is perhaps the most common function for loading tabular data. It's highly flexible and can handle various delimiters, headers, and encoding options.

In [17]:
# Create a dummy CSV file for demonstration
data_csv = """Name,Age,City
Alice,25,New York
Bob,30,Los Angeles
Charlie,35,Chicago"""

with open('sample.csv', 'w') as f:
    f.write(data_csv)

# Read a CSV file
df_csv = pd.read_csv('sample.csv')
print("DataFrame from CSV:")
display(df_csv)

DataFrame from CSV:

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

**`pd.read_json()`: Reading from JSON files**

JSON (JavaScript Object Notation) is another popular format, especially for web-based data. Pandas can directly read JSON strings or files.

In [18]:
# Create a dummy JSON file for demonstration
data_json = '''
[
    {"Name": "David", "Age": 40, "City": "Houston"},
    {"Name": "Eve", "Age": 28, "City": "Miami"}
]
'''
with open('sample.json', 'w') as f:
    f.write(data_json)

# Read a JSON file
df_json = pd.read_json('sample.json')
print("\nDataFrame from JSON:")
display(df_json)

DataFrame from JSON:

    Name  Age     City
0  David   40  Houston
1    Eve   28    Miami

### Writing Files

Just as easily as reading, Pandas allows you to export your DataFrames back into various file formats using methods like `to_csv()`, `to_excel()`, and `to_json()`.

**`df.to_csv()`: Writing to CSV files**

This method writes the DataFrame to a CSV file. You can control whether to include the index, header, and other formatting options.

In [19]:
# Write df_csv to a new CSV file without the index
df_csv.to_csv('output.csv', index=False)
print("DataFrame written to 'output.csv' (check files tab).")

# You can verify by reading it back
df_output_csv = pd.read_csv('output.csv')
print("\nVerifying output.csv:")
display(df_output_csv)

DataFrame written to 'output.csv' (check files tab).

Verifying output.csv:

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

### Working with Large Datasets using `chunksize`

For very large files that don't fit into memory, Pandas' `read_csv()` and `read_json()` functions offer a `chunksize` parameter. This allows you to read the file in smaller, manageable chunks, process each chunk, and then combine or aggregate the results.

This approach is essential for memory-efficient processing of big data.

In [20]:
# Create a large dummy CSV file (e.g., 1000 rows)
import numpy as np
large_data_rows = []
for i in range(1000):
    large_data_rows.append(f"{np.random.randint(1, 100)},{np.random.rand():.6f},text_{i}")

with open('large_sample.csv', 'w') as f:
    f.write("col1,col2,col3\n")
    f.write("\n".join(large_data_rows))

# Read the large CSV file in chunks
chunk_size = 200
chunks = []

for chunk in pd.read_csv('large_sample.csv', chunksize=chunk_size):
    # Process each chunk (e.g., filter, transform, aggregate)
    # For this example, we'll just store the chunks
    chunks.append(chunk)
    print(f"Read a chunk of {len(chunk)} rows.")

# Concatenate all chunks into a single DataFrame if needed
df_large_processed = pd.concat(chunks, ignore_index=True)
print(f"\nTotal rows processed: {len(df_large_processed)}")
display(df_large_processed.head())

Read a chunk of 200 rows.
Read a chunk of 200 rows.
Read a chunk of 200 rows.
Read a chunk of 200 rows.
Read a chunk of 200 rows.

Total rows processed: 1000

   col1      col2    col3
0    10  0.848908  text_0
1    61  0.413851  text_1
2    73  0.220316  text_2
3    26  0.962362  text_3
4    82  0.985635  text_4

## Module 4: Data Inspection & Exploration (EDA Start)

After loading your data, the first crucial step in any data analysis workflow is to inspect and explore it. This process, often called Exploratory Data Analysis (EDA), helps you understand the data's structure, identify potential issues (like missing values or incorrect data types), and gain initial insights. Pandas provides several convenient methods for quick data inspection.

### Quick Data Overviews: `head()`, `tail()`, `info()`, `describe()`

These methods are your first look at the data, offering snapshots of its rows, columns, data types, and statistical summaries.

*   **`df.head(n)`**: Returns the first `n` rows of the DataFrame (default is 5).
*   **`df.tail(n)`**: Returns the last `n` rows of the DataFrame (default is 5).
*   **`df.info()`**: Provides a concise summary of a DataFrame, including data types of each column, non-null values, and memory usage.
*   **`df.describe()`**: Generates descriptive statistics of numerical columns, including count, mean, standard deviation, min, max, and quartiles. For `object` (string) columns, it provides count, unique, top, and freq.

In [21]:
# Using the 'data_frame' created in Module 2 for demonstration

print("First 5 rows (data_frame.head()):")
display(data_frame.head())

print("\nLast 2 rows (data_frame.tail(2)):")
display(data_frame.tail(2))

print("\nDataFrame Info (data_frame.info()):")
data_frame.info()

print("\nDescriptive Statistics (data_frame.describe()):")
display(data_frame.describe())

First 5 rows (data_frame.head()):

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

Last 2 rows (data_frame.tail(2)):

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

DataFrame Info (data_frame.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Descriptive Statistics (data_frame.describe()):

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

### Understanding Data Dimensions: `shape`, `columns`, `dtypes`

Beyond basic summaries, you'll often need to know the exact dimensions, column names, and their data types.

*   **`df.shape`**: Returns a tuple representing the dimensions of the DataFrame (rows, columns).
*   **`df.columns`**: Returns an Index object containing the column labels of the DataFrame.
*   **`df.dtypes`**: Returns a Series with the data type of each column.

In [22]:
print("DataFrame Shape (data_frame.shape):", data_frame.shape)
print("\nDataFrame Columns (data_frame.columns):", data_frame.columns.tolist())
print("\nDataFrame Data Types (data_frame.dtypes):")
display(data_frame.dtypes)

DataFrame Shape (data_frame.shape): (4, 3)

DataFrame Columns (data_frame.columns): ['Name', 'Age', 'City']

DataFrame Data Types (data_frame.dtypes):

Name    object
Age      int64
City    object
dtype: object

### Value Counts and Uniqueness: `value_counts()`, `unique()`, `nunique()`

These methods are essential for understanding the distribution and variety of values within columns, especially for categorical data.

*   **`Series.value_counts()`**: Returns a Series containing counts of unique values. The resulting object will be in descending order so that the first element is the most frequently occurring element. Excludes NA values by default.
*   **`Series.unique()`**: Returns an array of unique values in the Series.
*   **`Series.nunique()`**: Returns the number of unique values in the Series (excluding NaN by default).

In [23]:
print("Value Counts for 'City' (data_frame['City'].value_counts()):")
display(data_frame['City'].value_counts())

print("\nUnique values in 'City' (data_frame['City'].unique()):")
display(data_frame['City'].unique())

print("\nNumber of unique cities (data_frame['City'].nunique()):", data_frame['City'].nunique())

Value Counts for 'City' (data_frame['City'].value_counts()):

City
New York       1
Los Angeles    1
Chicago        1
Houston        1
Name: count, dtype: int64

Unique values in 'City' (data_frame['City'].unique()):

array(['New York', 'Los Angeles', 'Chicago', 'Houston'], dtype=object)

Number of unique cities (data_frame['City'].nunique()): 4

## Module 5: Data Selection & Indexing

Data selection and indexing are fundamental operations in Pandas, allowing you to extract specific subsets of your data for analysis or manipulation. Pandas offers several powerful and flexible ways to select data, primarily through column access, row selection using labels (`.loc[]`) and integer-location (`.iloc[]`), and boolean indexing.

### 5.1 Selecting Columns

You can select one or multiple columns from a DataFrame. This returns either a Series (for a single column) or another DataFrame (for multiple columns).

**Selecting a Single Column:**

To select a single column, you can use dictionary-like notation or dot notation (if the column name is a valid Python identifier and doesn't conflict with DataFrame methods).

In [24]:
# Select a single column (returns a Series)
names = data_frame['Name']
print("Selecting 'Name' column (Series):")
display(names)

# Alternative using dot notation (if column name allows)
ages = data_frame.Age
print("\nSelecting 'Age' column (dot notation):")
display(ages)

Selecting 'Name' column (Series):

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

Selecting 'Age' column (dot notation):

0    25
1    30
2    35
3    40
Name: Age, dtype: int64

**Selecting Multiple Columns:**

To select multiple columns, pass a list of column names to the DataFrame.

In [25]:
# Select multiple columns (returns a DataFrame)
name_age = data_frame[['Name', 'Age']]
print("\nSelecting 'Name' and 'Age' columns (DataFrame):")
display(name_age)

Selecting 'Name' and 'Age' columns (DataFrame):

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

### 5.2 Selecting Rows with `.loc[]` and `.iloc[]`

Pandas provides two primary methods for selecting rows (and columns) based on their labels or integer positions:

*   **`.loc[]`**: Primarily label-based indexing. It can take a single label, a list of labels, a slice of labels, or a boolean array.
*   **`.iloc[]`**: Primarily integer-location based indexing. It can take a single integer, a list of integers, a slice of integers, or a boolean array.

**Using `.loc[]` (Label-based indexing):**

`loc` is used with row and column labels.

In [26]:
# Select a single row by label (index)
row_0_loc = data_frame.loc[0]
print("Selecting row with label 0 using .loc:")
display(row_0_loc)

# Select multiple rows by labels
rows_0_2_loc = data_frame.loc[[0, 2]]
print("\nSelecting rows with labels 0 and 2 using .loc:")
display(rows_0_2_loc)

# Select rows and specific columns by labels
rows_cols_loc = data_frame.loc[0:2, ['Name', 'City']]
print("\nSelecting rows 0-2 and 'Name', 'City' columns using .loc:")
display(rows_cols_loc)

Selecting row with label 0 using .loc:

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

Selecting rows with labels 0 and 2 using .loc:

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

Selecting rows 0-2 and 'Name', 'City' columns using .loc:

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

**Using `.iloc[]` (Integer-location based indexing):**

`iloc` is used with integer positions, just like standard Python indexing.

In [27]:
# Select a single row by integer position
row_1_iloc = data_frame.iloc[1]
print("Selecting row at integer position 1 using .iloc:")
display(row_1_iloc)

# Select multiple rows by integer positions
rows_1_3_iloc = data_frame.iloc[[1, 3]]
print("\nSelecting rows at integer positions 1 and 3 using .iloc:")
display(rows_1_3_iloc)

# Select rows and specific columns by integer positions
rows_cols_iloc = data_frame.iloc[0:2, [0, 2]] # rows 0 to 1, columns 0 and 2
print("\nSelecting rows 0-1 and columns 0, 2 using .iloc:")
display(rows_cols_iloc)

Selecting row at integer position 1 using .iloc:

Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object

Selecting rows at integer positions 1 and 3 using .iloc:

    Name  Age         City
1    Bob   30  Los Angeles
3  David   40      Houston

Selecting rows 0-1 and columns 0, 2 using .iloc:

    Name         City
0  Alice     New York
1    Bob  Los Angeles

### 5.3 Boolean Indexing (Filtering Data)

Boolean indexing, also known as boolean masking, is a powerful way to filter data based on conditions. You pass a boolean Series (or array) to the DataFrame, and only rows where the condition is `True` are returned.

**Filtering with a Single Condition:**

In [28]:
# Filter rows where 'Age' is greater than 30
filtered_df = data_frame[data_frame['Age'] > 30]
print("DataFrame where Age > 30:")
display(filtered_df)

# Filter rows where 'City' is 'New York'
from_ny = data_frame[data_frame['City'] == 'New York']
print("\nDataFrame where City is 'New York':")
display(from_ny)

DataFrame where Age > 30:

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

DataFrame where City is 'New York':

    Name  Age      City
0  Alice   25  New York

**Filtering with Multiple Conditions (AND / OR):**

Combine multiple conditions using `&` (AND) or `|` (OR) operators. Remember to wrap each condition in parentheses.

In [29]:
# Multiple conditions with AND (&)
# Select people older than 30 AND living in Chicago
complex_condition = (data_frame['Age'] > 30) & (data_frame['City'] == 'Chicago')
aged_over_30 = data_frame[complex_condition]
print("DataFrame where Age > 30 AND City == 'Chicago':")
display(aged_over_30)

# Multiple conditions with OR (|)
# Select people from New York OR Chicago
complex_condition_or = (data_frame['City'] == 'New York') | (data_frame['City'] == 'Chicago')
filtered_df_or = data_frame[complex_condition_or]
print("\nDataFrame where City is 'New York' OR 'Chicago':")
display(filtered_df_or)

DataFrame where Age > 30 AND City == 'Chicago':

      Name  Age     City
2  Charlie   35  Chicago

DataFrame where City is 'New York' OR 'Chicago':

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

### 5.4 Using `.isin()` for Multiple Value Filtering

The `.isin()` method is very useful for filtering when you want to select rows where a column's value is one of several possible values.

In [30]:
# Filter rows where 'City' is either 'New York' or 'Chicago'
cities_of_interest = ['New York', 'Chicago']
filtered_by_list = data_frame[data_frame['City'].isin(cities_of_interest)]
print("DataFrame where City is in ['New York', 'Chicago'] using .isin():")
display(filtered_by_list)

DataFrame where City is in ['New York', 'Chicago'] using .isin():

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

## Module 6: Data Cleaning & Preprocessing

Data cleaning and preprocessing are critical steps in any data analysis pipeline. Raw data is often messy, containing missing values, duplicates, incorrect data types, or outliers. This module will cover fundamental techniques using Pandas to address these common issues, making your data ready for analysis.

### 6.1 Handling Missing Data

Missing data is a common problem. Pandas represents missing values as `NaN` (Not a Number) for numerical columns and `None` or `NaN` for object/string columns. Effectively dealing with missing data is crucial as many analytical tools cannot handle `NaN`s.

Key methods:
*   **`isnull()` / `isna()`**: Returns a boolean DataFrame indicating where values are missing.
*   **`notnull()` / `notna()`**: Returns a boolean DataFrame indicating where values are not missing.
*   **`dropna()`**: Removes rows or columns containing missing values.
*   **`fillna()`**: Fills missing values with a specified value or using a method (e.g., forward-fill, back-fill, mean, median).

**Creating a DataFrame with Missing Values for Demonstration:**

In [31]:
data_missing = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [10, 20, 30, np.nan, 50]
}
df_missing = pd.DataFrame(data_missing)
print("Original DataFrame with missing values:")
display(df_missing)

Original DataFrame with missing values:

     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  NaN  3.0  30.0
3  4.0  4.0   NaN
4  5.0  NaN  50.0

**Checking for Missing Values:**

In [32]:
print("DataFrame.isnull():")
display(df_missing.isnull())

print("\nSum of missing values per column:")
display(df_missing.isnull().sum())

print("\nTotal number of missing values:")
display(df_missing.isnull().sum().sum())

DataFrame.isnull():

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True
4  False   True  False

Sum of missing values per column:

A    1
B    2
C    1
dtype: int64

Total number of missing values:

np.int64(4)

**Dropping Missing Values:**

In [33]:
# Drop rows with any missing values
df_dropped_rows = df_missing.dropna()
print("DataFrame after dropping rows with any NaN:")
display(df_dropped_rows)

# Drop columns with any missing values
df_dropped_cols = df_missing.dropna(axis=1)
print("\nDataFrame after dropping columns with any NaN:")
display(df_dropped_cols)

# Drop rows only if ALL values are missing (not applicable in this example)
df_dropped_all_na = df_missing.dropna(how='all')
print("\nDataFrame after dropping rows where all values are NaN (no change here):")
display(df_dropped_all_na)

DataFrame after dropping rows with any NaN:

     A    B     C
1  2.0  2.0  20.0

DataFrame after dropping columns with any NaN:

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

DataFrame after dropping rows where all values are NaN (no change here):

     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  NaN  3.0  30.0
3  4.0  4.0   NaN
4  5.0  NaN  50.0

**Filling Missing Values:**

In [34]:
# Fill with a constant value (e.g., 0)
df_filled_zero = df_missing.fillna(0)
print("DataFrame after filling NaN with 0:")
display(df_filled_zero)

# Fill with the mean of each column
df_filled_mean = df_missing.fillna(df_missing.mean())
print("\nDataFrame after filling NaN with column means:")
display(df_filled_mean)

# Forward-fill (propagate last valid observation forward to next valid)
df_ffill = df_missing.fillna(method='ffill')
print("\nDataFrame after forward-fill:")
display(df_ffill)

# Back-fill (propagate next valid observation backward to next valid)
df_bfill = df_missing.fillna(method='bfill')
print("\nDataFrame after back-fill:")
display(df_bfill)

DataFrame after filling NaN with 0:

     A    B     C
0  1.0  0.0  10.0
1  2.0  2.0  20.0
2  0.0  3.0  30.0
3  4.0  4.0   0.0
4  5.0  0.0  50.0

DataFrame after filling NaN with column means:

     A    B     C
0  1.0  3.0  10.0
1  2.0  2.0  20.0
2  3.0  3.0  30.0
3  4.0  4.0  27.5
4  5.0  3.0  50.0

DataFrame after forward-fill:

/tmp/ipykernel_693/215757073.py:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df_missing.fillna(method='ffill')

     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  2.0  3.0  30.0
3  4.0  4.0  30.0
4  5.0  4.0  50.0

DataFrame after back-fill:

/tmp/ipykernel_693/215757073.py:17: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df_missing.fillna(method='bfill')

     A    B     C
0  1.0  2.0  10.0
1  2.0  2.0  20.0
2  4.0  3.0  30.0
3  4.0  4.0  50.0
4  5.0  NaN  50.0

**Conditional Filling (e.g., group-wise mean):**

Sometimes, filling missing values based on groups is more appropriate.

In [35]:
# Create a DataFrame for group-wise filling
df_with_na = pd.DataFrame({
    'Group': ['A', 'A', 'B', 'B', 'A'],
    'Value': [10, np.nan, 20, np.nan, 15]
})
print("Original DataFrame for group-wise filling:")
display(df_with_na)

# Fill NaN values with the mean of their respective groups
df_with_na['Value_Filled_Group_Mean'] = df_with_na.groupby('Group')['Value'].transform(lambda x: x.fillna(x.mean()))
print("\nDataFrame after filling NaN with group-wise mean:")
display(df_with_na)

Original DataFrame for group-wise filling:

  Group  Value
0     A   10.0
1     A    NaN
2     B   20.0
3     B    NaN
4     A   15.0

DataFrame after filling NaN with group-wise mean:

  Group  Value  Value_Filled_Group_Mean
0     A   10.0                     10.0
1     A    NaN                     12.5
2     B   20.0                     20.0
3     B    NaN                     20.0
4     A   15.0                     15.0

### 6.2 Handling Duplicate Data

Duplicate rows can skew analysis and lead to incorrect conclusions. Pandas provides methods to identify and remove duplicate entries.

Key methods:
*   **`duplicated()`**: Returns a boolean Series indicating whether each row is a duplicate of a previous row.
*   **`drop_duplicates()`**: Removes duplicate rows.

**Creating a DataFrame with Duplicate Values for Demonstration:**

In [36]:
data_duplicates = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'City': ['NY', 'LA', 'NY', 'CHI', 'LA']
}
df_duplicates = pd.DataFrame(data_duplicates)
print("Original DataFrame with duplicates:")
display(df_duplicates)

Original DataFrame with duplicates:

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
2    Alice   25   NY
3  Charlie   35  CHI
4      Bob   30   LA

**Identifying Duplicates:**

In [37]:
print("Boolean Series indicating duplicated rows:")
display(df_duplicates.duplicated())

print("\nDuplicated rows themselves (keeping the first occurrence):")
display(df_duplicates[df_duplicates.duplicated()])

Boolean Series indicating duplicated rows:

0    False
1    False
2     True
3    False
4     True
dtype: bool

Duplicated rows themselves (keeping the first occurrence):

    Name  Age City
2  Alice   25   NY
4    Bob   30   LA

**Removing Duplicates:**

In [38]:
# Remove all duplicate rows (keeps the first occurrence by default)
df_no_duplicates = df_duplicates.drop_duplicates()
print("DataFrame after dropping all duplicate rows:")
display(df_no_duplicates)

# Remove duplicates based on a subset of columns (e.g., 'Name' and 'Age')
df_no_duplicates_subset = df_duplicates.drop_duplicates(subset=['Name', 'Age'])
print("\nDataFrame after dropping duplicates based on 'Name' and 'Age':")
display(df_no_duplicates_subset)

# Keep the last occurrence of duplicates instead of the first
df_no_duplicates_last = df_duplicates.drop_duplicates(keep='last')
print("\nDataFrame after dropping duplicates, keeping the last occurrence:")
display(df_no_duplicates_last)

DataFrame after dropping all duplicate rows:

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   35  CHI

DataFrame after dropping duplicates based on 'Name' and 'Age':

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
3  Charlie   35  CHI

DataFrame after dropping duplicates, keeping the last occurrence:

      Name  Age City
2    Alice   25   NY
3  Charlie   35  CHI
4      Bob   30   LA

### 6.3 Changing Data Types (Type Conversion)

Incorrect data types can lead to errors or inefficient operations. Pandas allows you to convert data types using `astype()`, `to_numeric()`, `to_datetime()`, etc.

Common reasons for type conversion:
*   **Memory efficiency**: Using smaller integer types if appropriate.
*   **Correctness**: Ensuring numerical operations on numbers, string operations on strings.
*   **Functionality**: Converting to datetime objects for time-series analysis.

**Using `astype()`:**

In [39]:
# Convert 'Age' column from int64 to float64
df_age_float = data_frame['Age'].astype(float)
print("Original 'Age' dtype:", data_frame['Age'].dtype)
print("Converted 'Age' Series dtype:", df_age_float.dtype)
display(df_age_float)

# Convert back to int64 (will error if NaNs are present)
# df_age_int = df_age_float.astype(int) # This would work if no NaNs were introduced

# Example with a DataFrame column
df_copy = data_frame.copy()
df_copy['Age'] = df_copy['Age'].astype('float32')
print("\nDataFrame 'Age' column converted to float32:")
display(df_copy.dtypes)

Original 'Age' dtype: int64
Converted 'Age' Series dtype: float64

0    25.0
1    30.0
2    35.0
3    40.0
Name: Age, dtype: float64

DataFrame 'Age' column converted to float32:

Name     object
Age     float32
City     object
dtype: object

**Using `pd.to_numeric()`:**

This is robust for converting columns that might contain non-numeric strings to numeric types. The `errors` parameter is particularly useful:
*   `errors='raise'` (default): Raise an error if invalid parsing occurs.
*   `errors='coerce'`: Invalid parsing will be set as `NaN`.
*   `errors='ignore'`: Return the input unchanged on error.

In [40]:
# Create a Series with mixed types (string and int)
string_numbers = pd.Series(['10', '20', '30', '40'])
df_str_num = pd.DataFrame({'Value': string_numbers})
print("Original Series with string numbers:")
display(df_str_num)
print("Original dtype:", df_str_num['Value'].dtype)

# Convert to numeric, coercing errors
df_str_num['Value'] = pd.to_numeric(df_str_num['Value'], errors='coerce')
print("\nSeries after pd.to_numeric with errors='coerce':")
display(df_str_num)
print("New dtype:", df_str_num['Value'].dtype)

Original Series with string numbers:

  Value
0    10
1    20
2    30
3    40

Original dtype: object

Series after pd.to_numeric with errors='coerce':

   Value
0     10
1     20
2     30
3     40

New dtype: int64

**Using `pd.to_datetime()`:**

Essential for working with dates and times. It can parse various string formats into datetime objects.

In [41]:
data_dt = {
    'OrderID': [1, 2, 3, 4, 5],
    'Customer': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'OrderDate': ['2023-01-15', '2023-01-16', '2023-02-01', '2023-02-02', '2023-03-10'],
    'Amount': [100.50, 75.25, 200.00, 50.00, 120.75]
}
df_datetime_sample = pd.DataFrame(data_dt)

print("Original DataFrame with 'OrderDate' as object dtype:")
display(df_datetime_sample.info())

# Convert 'OrderDate' to datetime objects
df_datetime_sample['OrderDate'] = pd.to_datetime(df_datetime_sample['OrderDate'])

print("\nDataFrame after converting 'OrderDate' to datetime dtype:")
display(df_datetime_sample.info())
display(df_datetime_sample.head())

Original DataFrame with 'OrderDate' as object dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      object
 3   Amount     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

None

DataFrame after converting 'OrderDate' to datetime dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      datetime64[ns]
 3   Amount     5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 292.0+ bytes

None

   OrderID Customer  OrderDate  Amount
0        1    Alice 2023-01-15  100.50
1        2      Bob 2023-01-16   75.25
2        3  Charlie 2023-02-01  200.00
3        4    David 2023-02-02   50.00
4        5      Eve 2023-03-10  120.75

**Converting to Categorical Type:**

Categorical data types are highly memory-efficient for columns with a limited number of unique values (e.g., 'Gender', 'Region'). They can also speed up certain operations.

In [42]:
df_cat = data_frame.copy()
df_cat['City'] = df_cat['City'].astype('category')

print("Original 'City' dtype:", data_frame['City'].dtype)
print("Converted 'City' dtype:", df_cat['City'].dtype)
display(df_cat.head())

Original 'City' dtype: object
Converted 'City' dtype: category

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## Module 7: Data Manipulation & Transformation

Data manipulation and transformation are crucial steps in feature engineering and preparing data for modeling. Pandas offers a rich set of functionalities to modify, reshape, and enhance your DataFrames. This module covers essential techniques for changing column names, reindexing, adding and removing columns, and applying functions.

### 7.1 Renaming Columns

Clarity in column names is vital for readability and maintainability. You can rename columns using the `.rename()` method or by directly assigning a new list of column names.

**Using `.rename()`:**

The `.rename()` method allows you to rename specific columns without affecting others. It takes a dictionary mapping old column names to new ones.

In [43]:
# Rename a single column
df_renamed_single = data_frame.rename(columns={'Name': 'Full Name'})
print("DataFrame after renaming 'Name' to 'Full Name':")
display(df_renamed_single)

# Rename multiple columns
df_renamed_multiple = data_frame.rename(columns={'Name': 'CustomerName', 'Age': 'CustomerAge'})
print("\nDataFrame after renaming multiple columns:")
display(df_renamed_multiple)

DataFrame after renaming 'Name' to 'Full Name':

  Full Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3     David   40      Houston

DataFrame after renaming multiple columns:

  CustomerName  CustomerAge         City
0        Alice           25     New York
1          Bob           30  Los Angeles
2      Charlie           35      Chicago
3        David           40      Houston

### 7.2 Reindexing

Reindexing changes the row labels and potentially the order of rows in a DataFrame. It's useful for conforming a DataFrame to a new index, which can involve adding, dropping, or reordering entries.

In [44]:
# Create a DataFrame with 'Name' as index for reindexing demonstration
df_index = data_frame.set_index('Name')
print("Original DataFrame with 'Name' as index:")
display(df_index)

# Reindex with a new order, adding a new index entry with NaN values
new_index = ['David', 'Alice', 'Charlie', 'Eve'] # 'Eve' is new
df_reindexed = df_index.reindex(new_index)
print("\nDataFrame after reindexing:")
display(df_reindexed)

Original DataFrame with 'Name' as index:

         Age         City
Name
Alice     25     New York
Bob       30  Los Angeles
Charlie   35      Chicago
David     40      Houston

DataFrame after reindexing:

          Age      City
Name
David    40.0   Houston
Alice    25.0  New York
Charlie  35.0   Chicago
Eve       NaN       NaN

### 7.3 Adding and Removing Columns

Modifying the structure of your DataFrame by adding new columns (e.g., derived from existing data) or dropping unnecessary ones is a frequent operation.

**Adding New Columns:**

New columns can be added by assignment, often based on calculations involving existing columns or by assigning a Series or scalar value.

In [45]:
# Add a new column 'Experience' with a list of values
data_frame['Experience'] = [5, 2, 10, 7]
print("DataFrame after adding 'Experience' column:")
display(data_frame)

# Add a column 'Age_Plus_5' based on an existing column
data_frame['Age_Plus_5'] = data_frame['Age'] + 5
print("\nDataFrame after adding 'Age_Plus_5' column:")
display(data_frame)

# Add a categorical column based on a condition
data_frame['Age_Group'] = pd.cut(data_frame['Age'], bins=[0, 29, 39, 100], labels=['<30', '30-39', '40+'])
print("\nDataFrame after adding 'Age_Group' column:")
display(data_frame)

DataFrame after adding 'Experience' column:

      Name  Age         City  Experience
0    Alice   25     New York           5
1      Bob   30  Los Angeles           2
2  Charlie   35      Chicago          10
3    David   40      Houston           7

DataFrame after adding 'Age_Plus_5' column:

      Name  Age         City  Experience  Age_Plus_5
0    Alice   25     New York           5          30
1      Bob   30  Los Angeles           2          35
2  Charlie   35      Chicago          10          40
3    David   40      Houston           7          45

DataFrame after adding 'Age_Group' column:

      Name  Age         City  Experience  Age_Plus_5 Age_Group
0    Alice   25     New York           5          30       <30
1      Bob   30  Los Angeles           2          35     30-39
2  Charlie   35      Chicago          10          40     30-39
3    David   40      Houston           7          45       40+

**Removing Columns:**

Columns can be removed using `drop()` method or by using the `del` keyword.

In [46]:
# Drop a single column using drop()
df_no_experience = data_frame.drop('Experience', axis=1)
print("DataFrame after dropping 'Experience' column:")
display(df_no_experience)

# Drop multiple columns
df_less_cols = data_frame.drop(columns=['Age_Plus_5', 'Age_Group'])
print("\nDataFrame after dropping 'Age_Plus_5' and 'Age_Group' columns:")
display(df_less_cols)

# Using 'del' keyword (modifies DataFrame in place)
df_copy_del = data_frame.copy()
del df_copy_del['City']
print("\nDataFrame after deleting 'City' column using del:")
display(df_copy_del)

DataFrame after dropping 'Experience' column:

      Name  Age         City  Age_Plus_5 Age_Group
0    Alice   25     New York          30       <30
1      Bob   30  Los Angeles          35     30-39
2  Charlie   35      Chicago          40     30-39
3    David   40      Houston          45       40+

DataFrame after dropping 'Age_Plus_5' and 'Age_Group' columns:

      Name  Age         City  Experience
0    Alice   25     New York           5
1      Bob   30  Los Angeles           2
2  Charlie   35      Chicago          10
3    David   40      Houston           7

DataFrame after deleting 'City' column using del:

      Name  Age  Experience  Age_Plus_5 Age_Group
0    Alice   25           5          30       <30
1      Bob   30           2          35     30-39
2  Charlie   35          10          40     30-39
3    David   40           7          45       40+

### 7.4 Applying Functions: `apply()`, `map()`, `applymap()`

These methods are powerful for applying custom logic or functions to your data. They differ in their application scope:
*   **`Series.apply()`**: Applies a function along *one axis* of a DataFrame (i.e., to each column or each row) or to each element of a Series.
*   **`DataFrame.apply()`**: Applies a function along *either axis* of a DataFrame.
*   **`Series.map()`**: Maps values of a Series to another set of values, usually using a dictionary or a Series. It's element-wise.
*   **`DataFrame.applymap()`**: Applies a function element-wise to an entire DataFrame (deprecated since Pandas 2.1, use `DataFrame.map()` instead for element-wise operations on DataFrames).

**Using `apply()` on Series (e.g., a column):**

In [47]:
# Apply a lambda function to convert 'Name' to uppercase
data_frame['Name_Upper'] = data_frame['Name'].apply(lambda x: x.upper())
print("DataFrame with 'Name_Upper' column (uppercase names):")
display(data_frame)

DataFrame with 'Name_Upper' column (uppercase names):

      Name  Age         City  Experience  Age_Plus_5 Age_Group Name_Upper
0    Alice   25     New York           5          30       <30      ALICE
1      Bob   30  Los Angeles           2          35     30-39        BOB
2  Charlie   35      Chicago          10          40     30-39    CHARLIE
3    David   40      Houston           7          45       40+      DAVID

**Using `apply()` on DataFrame (row-wise or column-wise):**

In [48]:
# Apply a function to calculate the sum of 'Age' and 'Experience' for each row
def sum_age_experience(row):
    return row['Age'] + row['Experience']

data_frame['Age_Exp_Sum'] = data_frame.apply(sum_age_experience, axis=1)
print("DataFrame with 'Age_Exp_Sum' column (sum of Age and Experience):")
display(data_frame)

DataFrame with 'Age_Exp_Sum' column (sum of Age and Experience):

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum
0,Alice,25,New York,5,30,<30,ALICE,30
1,Bob,30,Los Angeles,2,35,30-39,BOB,32
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45
3,David,40,Houston,7,45,40+,DAVID,47

**Using `map()` on a Series:**

`map()` is optimized for element-wise transformations on a Series, especially when using a dictionary or another Series for mapping values.

In [49]:
# Create a dictionary to map cities to countries
country_map = {
    'New York': 'USA',
    'Los Angeles': 'USA',
    'Chicago': 'USA',
    'Houston': 'USA'
}

# Map 'City' column to 'Country' column
data_frame['Country'] = data_frame['City'].map(country_map)
print("DataFrame with 'Country' column (mapped from City):")
display(data_frame)

DataFrame with 'Country' column (mapped from City):

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

**Using `DataFrame.map()` for element-wise operations (Pandas 2.1+ recommendation):**

For element-wise operations across an entire DataFrame, `DataFrame.map()` is the recommended approach instead of `applymap()`.

In [50]:
# Example: Apply a simple multiplication to all numeric values in a copy of the DataFrame
df_numeric_op = data_frame[['Age', 'Experience', 'Age_Plus_5']].copy()
df_numeric_op = df_numeric_op.map(lambda x: x * 2)
print("DataFrame with numeric columns multiplied by 2 (using DataFrame.map()):")
display(df_numeric_op)

DataFrame with numeric columns multiplied by 2 (using DataFrame.map()):

   Age  Experience  Age_Plus_5
0   50          10          60
1   60           4          70
2   70          20          80
3   80          14          90

In [51]:
# Rename a single column
df_renamed_single = data_frame.rename(columns={'Name': 'Full Name'})
print("DataFrame after renaming 'Name' to 'Full Name':")
display(df_renamed_single)

# Rename multiple columns
df_renamed_multiple = data_frame.rename(columns={'Name': 'CustomerName', 'Age': 'CustomerAge'})
print("\nDataFrame after renaming multiple columns:")
display(df_renamed_multiple)

DataFrame after renaming 'Name' to 'Full Name':

,Full Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

DataFrame after renaming multiple columns:

,CustomerName,CustomerAge,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

In [52]:
# Create a DataFrame with 'Name' as index for reindexing demonstration
df_index = data_frame.set_index('Name')
print("Original DataFrame with 'Name' as index:")
display(df_index)

# Reindex with a new order, adding a new index entry with NaN values
new_index = ['David', 'Alice', 'Charlie', 'Eve'] # 'Eve' is new
df_reindexed = df_index.reindex(new_index)
print("\nDataFrame after reindexing:")
display(df_reindexed)

Original DataFrame with 'Name' as index:

,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
Name,,,,,,,,
Alice,25,New York,5,30,<30,ALICE,30,USA
Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
David,40,Houston,7,45,40+,DAVID,47,USA

DataFrame after reindexing:

,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
Name,,,,,,,,
David,40.0,Houston,7.0,45.0,40+,DAVID,47.0,USA
Alice,25.0,New York,5.0,30.0,<30,ALICE,30.0,USA
Charlie,35.0,Chicago,10.0,40.0,30-39,CHARLIE,45.0,USA
Eve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
# Add a new column 'Experience' with a list of values
data_frame['Experience'] = [5, 2, 10, 7]
print("DataFrame after adding 'Experience' column:")
display(data_frame)

# Add a column 'Age_Plus_5' based on an existing column
data_frame['Age_Plus_5'] = data_frame['Age'] + 5
print("\nDataFrame after adding 'Age_Plus_5' column:")
display(data_frame)

# Add a categorical column based on a condition
data_frame['Age_Group'] = pd.cut(data_frame['Age'], bins=[0, 29, 39, 100], labels=['<30', '30-39', '40+'])
print("\nDataFrame after adding 'Age_Group' column:")
display(data_frame)

DataFrame after adding 'Experience' column:

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

DataFrame after adding 'Age_Plus_5' column:

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

DataFrame after adding 'Age_Group' column:

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

In [54]:
# Drop a single column using drop()
df_no_experience = data_frame.drop('Experience', axis=1)
print("DataFrame after dropping 'Experience' column:")
display(df_no_experience)

# Drop multiple columns
df_less_cols = data_frame.drop(columns=['Age_Plus_5', 'Age_Group'])
print("\nDataFrame after dropping 'Age_Plus_5' and 'Age_Group' columns:")
display(df_less_cols)

# Using 'del' keyword (modifies DataFrame in place)
df_copy_del = data_frame.copy()
del df_copy_del['City']
print("\nDataFrame after deleting 'City' column using del:")
display(df_copy_del)

DataFrame after dropping 'Experience' column:

,Name,Age,City,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,40,30-39,CHARLIE,45,USA
3,David,40,Houston,45,40+,DAVID,47,USA

DataFrame after dropping 'Age_Plus_5' and 'Age_Group' columns:

      Name  Age         City  Experience Name_Upper  Age_Exp_Sum Country
0    Alice   25     New York           5      ALICE           30     USA
1      Bob   30  Los Angeles           2        BOB           32     USA
2  Charlie   35      Chicago          10    CHARLIE           45     USA
3    David   40      Houston           7      DAVID           47     USA

DataFrame after deleting 'City' column using del:

,Name,Age,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,5,30,<30,ALICE,30,USA
1,Bob,30,2,35,30-39,BOB,32,USA
2,Charlie,35,10,40,30-39,CHARLIE,45,USA
3,David,40,7,45,40+,DAVID,47,USA

In [55]:
# Apply a lambda function to convert 'Name' to uppercase
data_frame['Name_Upper'] = data_frame['Name'].apply(lambda x: x.upper())
print("DataFrame with 'Name_Upper' column (uppercase names):")
display(data_frame)

DataFrame with 'Name_Upper' column (uppercase names):

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

In [56]:
# Apply a function to calculate the sum of 'Age' and 'Experience' for each row
def sum_age_experience(row):
    return row['Age'] + row['Experience']

data_frame['Age_Exp_Sum'] = data_frame.apply(sum_age_experience, axis=1)
print("DataFrame with 'Age_Exp_Sum' column (sum of Age and Experience):")
display(data_frame)

DataFrame with 'Age_Exp_Sum' column (sum of Age and Experience):

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

In [57]:
# Create a dictionary to map cities to countries
country_map = {
    'New York': 'USA',
    'Los Angeles': 'USA',
    'Chicago': 'USA',
    'Houston': 'USA'
}

# Map 'City' column to 'Country' column
data_frame['Country'] = data_frame['City'].map(country_map)
print("DataFrame with 'Country' column (mapped from City):")
display(data_frame)

DataFrame with 'Country' column (mapped from City):

,Name,Age,City,Experience,Age_Plus_5,Age_Group,Name_Upper,Age_Exp_Sum,Country
0,Alice,25,New York,5,30,<30,ALICE,30,USA
1,Bob,30,Los Angeles,2,35,30-39,BOB,32,USA
2,Charlie,35,Chicago,10,40,30-39,CHARLIE,45,USA
3,David,40,Houston,7,45,40+,DAVID,47,USA

In [58]:
# Example: Apply a simple multiplication to all numeric values in a copy of the DataFrame
df_numeric_op = data_frame[['Age', 'Experience', 'Age_Plus_5']].copy()
df_numeric_op = df_numeric_op.map(lambda x: x * 2)
print("DataFrame with numeric columns multiplied by 2 (using DataFrame.map()):")
display(df_numeric_op)

DataFrame with numeric columns multiplied by 2 (using DataFrame.map()):

   Age  Experience  Age_Plus_5
0   50          10          60
1   60           4          70
2   70          20          80
3   80          14          90

## Module 8: Data Aggregation & Grouping

Data aggregation and grouping are fundamental operations for summarizing data and extracting meaningful insights. Pandas provides the incredibly versatile `groupby()` method, often used in conjunction with `agg()`, `pivot_table()`, and other reshaping functions.

### 8.1 Grouping with `groupby()`

The `groupby()` method is used to group data based on one or more columns, allowing you to perform aggregate functions (like sum, mean, count, min, max) on the grouped data. It follows a "split-apply-combine" strategy:
1.  **Split**: Divide the DataFrame into groups based on some criteria.
2.  **Apply**: Apply a function to each group independently.
3.  **Combine**: Combine the results into a DataFrame.

**Basic Aggregation after Grouping:**

In [59]:
# Create a sample DataFrame for grouping
df_sales = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'South', 'West', 'East', 'South'],
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'David', 'Charlie'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Sales': [100, 150, 120, 80, 200, 90, 110],
    'Orders': [10, 15, 12, 8, 20, 9, 11]
})
print("Original Sales DataFrame:")
display(df_sales)

# Group by 'Region' and calculate the sum of 'Sales'
total_sales_region = df_sales.groupby('Region')['Sales'].sum()
print("\nTotal Sales by Region:")
display(total_sales_region)

# Group by 'Region' and calculate the count of 'Orders'
order_counts = df_sales.groupby('Region')['Orders'].count()
print("\nOrder Counts by Region:")
display(order_counts)

Original Sales DataFrame:

  Region Salesperson Product  Sales  Orders
0   East       Alice       A    100      10
1   West         Bob       B    150      15
2   East       Alice       A    120      12
3  South     Charlie       C     80       8
4   West         Bob       B    200      20
5   East       David       A     90       9
6  South     Charlie       C    110      11

Total Sales by Region:

Region
East     310
South    190
West     350
Name: Sales, dtype: int64

Order Counts by Region:

Region
East     3
South    2
West     2
Name: Orders, dtype: int64

**Applying Multiple Aggregation Functions (`.agg()`):**

The `.agg()` method allows you to apply multiple aggregation functions to one or more columns simultaneously.

In [60]:
# Group by 'Region' and get the sum, mean, and count of 'Sales'
region_sales_summary = df_sales.groupby('Region')['Sales'].agg(['sum', 'mean', 'count'])
print("Sales Summary by Region (sum, mean, count):")
display(region_sales_summary)

# Apply different aggregations to different columns
multi_col_agg = df_sales.groupby('Region').agg(
    Total_Sales=('Sales', 'sum'),
    Avg_Orders=('Orders', 'mean'),
    Num_Salespersons=('Salesperson', 'nunique') # Count unique salespersons
)
print("\nCustom Aggregations by Region:")
display(multi_col_agg)

Sales Summary by Region (sum, mean, count):

        sum        mean  count
Region
East    310  103.333333      3
South   190   95.000000      2
West    350  175.000000      2

Custom Aggregations by Region:

        Total_Sales  Avg_Orders  Num_Salespersons
Region
East            310   10.333333                 2
South           190    9.500000                 1
West            350   17.500000                 1

**Grouping by Multiple Columns:**

You can group by more than one column to create hierarchical summaries.

In [61]:
# Group by 'Region' and 'Salesperson' and get the max 'Sales'
max_sales_person = df_sales.groupby(['Region', 'Salesperson'])['Sales'].max()
print("Max Sales by Region and Salesperson:")
display(max_sales_person)

# To get the result as a DataFrame with grouped columns as regular columns, use .reset_index()
avg_sales_person = df_sales.groupby('Salesperson')['Sales'].mean().reset_index()
print("\nAverage Sales by Salesperson (DataFrame format):")
display(avg_sales_person)

Max Sales by Region and Salesperson:

Region  Salesperson
East    Alice          120
        David           90
South   Charlie        110
West    Bob            200
Name: Sales, dtype: int64

Average Sales by Salesperson (DataFrame format):

  Salesperson  Sales
0       Alice  110.0
1         Bob  175.0
2     Charlie   95.0
3       David   90.0

### 8.2 Pivoting Data with `pivot_table()`

The `pivot_table()` function is a powerful tool to summarize and reshape data. It creates a spreadsheet-style pivot table as a DataFrame. It takes arguments for `index`, `columns`, `values`, and `aggfunc` (aggregation function).

In [62]:
# Simple pivot table: 'Region' as index, 'Product' as columns, sum of 'Sales' as values
pivot_sum = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='sum')
print("Pivot Table (Sum of Sales by Region and Product):")
display(pivot_sum)

# Pivot table with mean as aggregation function and filling NaN
pivot_basic = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='mean')
print("\nPivot Table (Mean of Sales by Region and Product, NaN as default):")
display(pivot_basic)

# Fill missing values in pivot table
pivot_filled = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='mean', fill_value=0)
print("\nPivot Table (Mean of Sales, NaN filled with 0):")
display(pivot_filled)

# Pivot table with multiple aggregation functions
pivot_multi_agg = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc=['sum', 'mean'])
print("\nPivot Table (Multiple Aggregations):")
display(pivot_multi_agg)

Pivot Table (Sum of Sales by Region and Product):

Product      A      B      C
Region
East     310.0    NaN    NaN
South      NaN    NaN  190.0
West       NaN  350.0    NaN

Pivot Table (Mean of Sales by Region and Product, NaN as default):

Product           A      B     C
Region
East     103.333333    NaN   NaN
South           NaN    NaN  95.0
West            NaN  175.0   NaN

Pivot Table (Mean of Sales, NaN filled with 0):

Product           A      B     C
Region
East     103.333333    0.0   0.0
South      0.000000    0.0  95.0
West       0.000000  175.0   0.0

Pivot Table (Multiple Aggregations):

           sum                      mean
Product      A      B      C           A      B     C
Region
East     310.0    NaN    NaN  103.333333    NaN   NaN
South      NaN    NaN  190.0         NaN    NaN  95.0
West       NaN  350.0    NaN         NaN  175.0   NaN

### 8.3 Reshaping Data with `melt()` and `stack()/unstack()`

These functions are used to transform the layout of tables. `melt()` is used to transform wide-format data into long-format data, while `stack()` and `unstack()` are used to pivot and unpivot hierarchical indices.

**`pd.melt()`: Unpivoting (Wide to Long Format)**

`melt()` is useful for transforming or "unpivoting" DataFrames from a wide format to a long format, making it easier for certain types of analysis or plotting.

In [63]:
# Create a wide-format DataFrame
df_pivot = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['New York', 'London', 'New York', 'London'],
    'Temperature': [10, 5, 12, 6],
    'Humidity': [80, 85, 78, 88]
})
print("Original Wide-format DataFrame:")
display(df_pivot)

# Melt the DataFrame to long format
df_melted = pd.melt(df_pivot, id_vars=['Date', 'City'], var_name='variable', value_name='value')
print("\nDataFrame after melting (long format):")
display(df_melted)

Original Wide-format DataFrame:

         Date      City  Temperature  Humidity
0  2023-01-01  New York           10        80
1  2023-01-01    London            5        85
2  2023-01-02  New York           12        78
3  2023-01-02    London            6        88

DataFrame after melting (long format):

         Date      City     variable  value
0  2023-01-01  New York  Temperature     10
1  2023-01-01    London  Temperature      5
2  2023-01-02  New York  Temperature     12
3  2023-01-02    London  Temperature      6
4  2023-01-01  New York     Humidity     80
5  2023-01-01    London     Humidity     85
6  2023-01-02  New York     Humidity     78
7  2023-01-02    London     Humidity     88

**`stack()` and `unstack()`: Pivoting with MultiIndex**

`stack()` pivots a level of the column labels to the row axis, producing a Series or DataFrame with a MultiIndex. `unstack()` does the inverse, pivoting a level of the (normally row) index to the column axis.

In [64]:
# Starting with a MultiIndex DataFrame (e.g., from a pivot_table with multiple aggregations)
multi_col_df = pd.pivot_table(df_sales, values=['Sales', 'Orders'], index=['Salesperson'], columns=['Region'], aggfunc='sum', fill_value=0)
print("Original DataFrame with MultiIndex columns (from pivot_table):")
display(multi_col_df)

# Stack the columns: pushes the last column level to the index
df_stacked = multi_col_df.stack()
print("\nDataFrame after stacking columns:")
display(df_stacked)

# Unstack the index: pushes the last index level to the columns
df_unstacked = df_stacked.unstack()
print("\nDataFrame after unstacking (back to original multi-column format):")
display(df_unstacked)

Original DataFrame with MultiIndex columns (from pivot_table):

            Orders            Sales
Region        East South West  East South West
Salesperson
Alice           22     0    0   220     0    0
Bob              0     0   35     0     0  350
Charlie          0    19    0     0   190    0
David            9     0    0    90     0    0

DataFrame after stacking columns:

/tmp/ipykernel_693/2975734511.py:7: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = multi_col_df.stack()

                    Orders  Sales
Salesperson Region
Alice       East        22    220
            South        0      0
            West         0      0
Bob         East         0      0
            South        0      0
            West        35    350
Charlie     East         0      0
            South       19    190
            West         0      0
David       East         9     90
            South        0      0
            West         0      0

DataFrame after unstacking (back to original multi-column format):

            Orders            Sales
Region        East South West  East South West
Salesperson
Alice           22     0    0   220     0    0
Bob              0     0   35     0     0  350
Charlie          0    19    0     0   190    0
David            9     0    0    90     0    0

In [65]:
# Create a sample DataFrame for grouping
df_sales = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'South', 'West', 'East', 'South'],
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'David', 'Charlie'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Sales': [100, 150, 120, 80, 200, 90, 110],
    'Orders': [10, 15, 12, 8, 20, 9, 11]
})
print("Original Sales DataFrame:")
display(df_sales)

# Group by 'Region' and calculate the sum of 'Sales'
total_sales_region = df_sales.groupby('Region')['Sales'].sum()
print("\nTotal Sales by Region:")
display(total_sales_region)

# Group by 'Region' and calculate the count of 'Orders'
order_counts = df_sales.groupby('Region')['Orders'].count()
print("\nOrder Counts by Region:")
display(order_counts)

Original Sales DataFrame:

  Region Salesperson Product  Sales  Orders
0   East       Alice       A    100      10
1   West         Bob       B    150      15
2   East       Alice       A    120      12
3  South     Charlie       C     80       8
4   West         Bob       B    200      20
5   East       David       A     90       9
6  South     Charlie       C    110      11

Total Sales by Region:

Region
East     310
South    190
West     350
Name: Sales, dtype: int64

Order Counts by Region:

Region
East     3
South    2
West     2
Name: Orders, dtype: int64

In [66]:
# Group by 'Region' and get the sum, mean, and count of 'Sales'
region_sales_summary = df_sales.groupby('Region')['Sales'].agg(['sum', 'mean', 'count'])
print("Sales Summary by Region (sum, mean, count):")
display(region_sales_summary)

# Apply different aggregations to different columns
multi_col_agg = df_sales.groupby('Region').agg(
    Total_Sales=('Sales', 'sum'),
    Avg_Orders=('Orders', 'mean'),
    Num_Salespersons=('Salesperson', 'nunique') # Count unique salespersons
)
print("\nCustom Aggregations by Region:")
display(multi_col_agg)

Sales Summary by Region (sum, mean, count):

        sum        mean  count
Region
East    310  103.333333      3
South   190   95.000000      2
West    350  175.000000      2

Custom Aggregations by Region:

        Total_Sales  Avg_Orders  Num_Salespersons
Region
East            310   10.333333                 2
South           190    9.500000                 1
West            350   17.500000                 1

In [67]:
# Group by 'Region' and 'Salesperson' and get the max 'Sales'
max_sales_person = df_sales.groupby(['Region', 'Salesperson'])['Sales'].max()
print("Max Sales by Region and Salesperson:")
display(max_sales_person)

# To get the result as a DataFrame with grouped columns as regular columns, use .reset_index()
avg_sales_person = df_sales.groupby('Salesperson')['Sales'].mean().reset_index()
print("\nAverage Sales by Salesperson (DataFrame format):")
display(avg_sales_person)

Max Sales by Region and Salesperson:

Region  Salesperson
East    Alice          120
        David           90
South   Charlie        110
West    Bob            200
Name: Sales, dtype: int64

Average Sales by Salesperson (DataFrame format):

  Salesperson  Sales
0       Alice  110.0
1         Bob  175.0
2     Charlie   95.0
3       David   90.0

In [68]:
# Simple pivot table: 'Region' as index, 'Product' as columns, sum of 'Sales' as values
pivot_sum = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='sum')
print("Pivot Table (Sum of Sales by Region and Product):")
display(pivot_sum)

# Pivot table with mean as aggregation function and filling NaN
pivot_basic = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='mean')
print("\nPivot Table (Mean of Sales by Region and Product, NaN as default):")
display(pivot_basic)

# Fill missing values in pivot table
pivot_filled = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc='mean', fill_value=0)
print("\nPivot Table (Mean of Sales, NaN filled with 0):")
display(pivot_filled)

# Pivot table with multiple aggregation functions
pivot_multi_agg = pd.pivot_table(df_sales, values='Sales', index='Region', columns='Product', aggfunc=['sum', 'mean'])
print("\nPivot Table (Multiple Aggregations):")
display(pivot_multi_agg)

Pivot Table (Sum of Sales by Region and Product):

Product      A      B      C
Region
East     310.0    NaN    NaN
South      NaN    NaN  190.0
West       NaN  350.0    NaN

Pivot Table (Mean of Sales by Region and Product, NaN as default):

Product           A      B     C
Region
East     103.333333    NaN   NaN
South           NaN    NaN  95.0
West            NaN  175.0   NaN

Pivot Table (Mean of Sales, NaN filled with 0):

Product           A      B     C
Region
East     103.333333    0.0   0.0
South      0.000000    0.0  95.0
West       0.000000  175.0   0.0

Pivot Table (Multiple Aggregations):

           sum                      mean
Product      A      B      C           A      B     C
Region
East     310.0    NaN    NaN  103.333333    NaN   NaN
South      NaN    NaN  190.0         NaN    NaN  95.0
West       NaN  350.0    NaN         NaN  175.0   NaN

In [69]:
# Create a wide-format DataFrame
df_pivot = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['New York', 'London', 'New York', 'London'],
    'Temperature': [10, 5, 12, 6],
    'Humidity': [80, 85, 78, 88]
})
print("Original Wide-format DataFrame:")
display(df_pivot)

# Melt the DataFrame to long format
df_melted = pd.melt(df_pivot, id_vars=['Date', 'City'], var_name='variable', value_name='value')
print("\nDataFrame after melting (long format):")
display(df_melted)

Original Wide-format DataFrame:

         Date      City  Temperature  Humidity
0  2023-01-01  New York           10        80
1  2023-01-01    London            5        85
2  2023-01-02  New York           12        78
3  2023-01-02    London            6        88

DataFrame after melting (long format):

         Date      City     variable  value
0  2023-01-01  New York  Temperature     10
1  2023-01-01    London  Temperature      5
2  2023-01-02  New York  Temperature     12
3  2023-01-02    London  Temperature      6
4  2023-01-01  New York     Humidity     80
5  2023-01-01    London     Humidity     85
6  2023-01-02  New York     Humidity     78
7  2023-01-02    London     Humidity     88

In [70]:
# Starting with a MultiIndex DataFrame (e.g., from a pivot_table with multiple aggregations)
multi_col_df = pd.pivot_table(df_sales, values=['Sales', 'Orders'], index=['Salesperson'], columns=['Region'], aggfunc='sum', fill_value=0)
print("Original DataFrame with MultiIndex columns (from pivot_table):")
display(multi_col_df)

# Stack the columns: pushes the last column level to the index
df_stacked = multi_col_df.stack()
print("\nDataFrame after stacking columns:")
display(df_stacked)

# Unstack the index: pushes the last index level to the columns
df_unstacked = df_stacked.unstack()
print("\nDataFrame after unstacking (back to original multi-column format):")
display(df_unstacked)

Original DataFrame with MultiIndex columns (from pivot_table):

            Orders            Sales
Region        East South West  East South West
Salesperson
Alice           22     0    0   220     0    0
Bob              0     0   35     0     0  350
Charlie          0    19    0     0   190    0
David            9     0    0    90     0    0

DataFrame after stacking columns:

/tmp/ipykernel_693/2975734511.py:7: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = multi_col_df.stack()

                    Orders  Sales
Salesperson Region
Alice       East        22    220
            South        0      0
            West         0      0
Bob         East         0      0
            South        0      0
            West        35    350
Charlie     East         0      0
            South       19    190
            West         0      0
David       East         9     90
            South        0      0
            West         0      0

DataFrame after unstacking (back to original multi-column format):

            Orders            Sales
Region        East South West  East South West
Salesperson
Alice           22     0    0   220     0    0
Bob              0     0   35     0     0  350
Charlie          0    19    0     0   190    0
David            9     0    0    90     0    0

## Module 9: Data Merging & Joining

One of the most common tasks in data analysis is combining different datasets. Pandas provides powerful tools to merge and join DataFrames based on common columns or indices, similar to SQL join operations.

### 9.1 Concatenating DataFrames (`pd.concat()`)

`pd.concat()` is used to append DataFrames either along the row axis (`axis=0`, default) or the column axis (`axis=1`). It stacks multiple DataFrames vertically or horizontally.

In [71]:
# Create two sample DataFrames
df_concat1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df_concat2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})

print("df_concat1:")
display(df_concat1)
print("\ndf_concat2:")
display(df_concat2)

# Concatenate along rows (default behavior, axis=0)
concat_rows = pd.concat([df_concat1, df_concat2])
print("\nConcatenated along rows:")
display(concat_rows)

# Concatenate along columns (axis=1)
concat_cols = pd.concat([df_concat1, df_concat2], axis=1)
print("\nConcatenated along columns:")
display(concat_cols)

# Concatenate with different columns, showing NaN for missing values
df_concat3 = pd.DataFrame({'C': ['C0', 'C1'], 'D': ['D0', 'D1']})
concat_diff_cols = pd.concat([df_concat1, df_concat3], axis=1)
print("\nConcatenated with different columns:")
display(concat_diff_cols)

df_concat1:

    A   B
0  A0  B0
1  A1  B1

df_concat2:

    A   B
0  A2  B2
1  A3  B3

Concatenated along rows:

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

Concatenated along columns:

    A   B   A   B
0  A0  B0  A2  B2
1  A1  B1  A3  B3

Concatenated with different columns:

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

### 9.2 Merging DataFrames (`pd.merge()`)

`pd.merge()` is Pandas' primary function for combining DataFrames based on shared columns (keys), similar to SQL's JOIN operations. You can specify the type of merge:
*   **`inner` (default):** Uses intersection of keys from both DataFrames.
*   **`left`:** Uses keys from left DataFrame, keeping all left rows.
*   **`right`:** Uses keys from right DataFrame, keeping all right rows.
*   **`outer`:** Uses union of keys from both DataFrames, keeping all rows.

In [72]:
# Create two sample DataFrames for merging
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
})
df2 = pd.DataFrame({
    'ID': [1, 3, 4, 5],
    'City': ['New York', 'Chicago', 'Houston', 'Miami'],
    'Salary': [70000, 80000, 90000, 60000]
})

print("df1:")
display(df1)
print("\ndf2:")
display(df2)

# Inner Merge (default)
inner_merge = pd.merge(df1, df2, on='ID', how='inner')
print("\nInner Merge (on ID):")
display(inner_merge)

# Left Merge
left_merge = pd.merge(df1, df2, on='ID', how='left')
print("\nLeft Merge (on ID):")
display(left_merge)

# Right Merge
right_merge = pd.merge(df1, df2, on='ID', how='right')
print("\nRight Merge (on ID):")
display(right_merge)

# Outer Merge
outer_merge = pd.merge(df1, df2, on='ID', how='outer')
print("\nOuter Merge (on ID):")
display(outer_merge)

df1:

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

df2:

   ID      City  Salary
0   1  New York   70000
1   3   Chicago   80000
2   4   Houston   90000
3   5     Miami   60000

Inner Merge (on ID):

   ID     Name  Age      City  Salary
0   1    Alice   25  New York   70000
1   3  Charlie   35   Chicago   80000
2   4    David   40   Houston   90000

Left Merge (on ID):

   ID     Name  Age      City   Salary
0   1    Alice   25  New York  70000.0
1   2      Bob   30       NaN      NaN
2   3  Charlie   35   Chicago  80000.0
3   4    David   40   Houston  90000.0

Right Merge (on ID):

   ID     Name   Age      City  Salary
0   1    Alice  25.0  New York   70000
1   3  Charlie  35.0   Chicago   80000
2   4    David  40.0   Houston   90000
3   5      NaN   NaN     Miami   60000

Outer Merge (on ID):

   ID     Name   Age      City   Salary
0   1    Alice  25.0  New York  70000.0
1   2      Bob  30.0       NaN      NaN
2   3  Charlie  35.0   Chicago  80000.0
3   4    David  40.0   Houston  90000.0
4   5      NaN   NaN     Miami  60000.0

### 9.3 Joining DataFrames (`.join()` method)

The `.join()` method is a convenient way to combine two DataFrames that have a common index (or one DataFrame's index with another's column). It defaults to a left join.

In [73]:
# Create two DataFrames with common indices
df_a = pd.DataFrame({'Value_A': [10, 20]}, index=['K1', 'K2'])
df_b = pd.DataFrame({'Value_B': [30, 40]}, index=['K1', 'K3'])

print("df_a:")
display(df_a)
print("\ndf_b:")
display(df_b)

# Left Join (default for .join())
joined_df = df_a.join(df_b)
print("\nLeft Join (df_a.join(df_b)):")
display(joined_df)

# Inner Join with .join()
inner_joined_df = df_a.join(df_b, how='inner')
print("\nInner Join (df_a.join(df_b, how='inner')):")
display(inner_joined_df)

# Joining on a column rather than index
df_c = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Dept': ['HR', 'IT', 'Sales']}, index=[1, 2, 3])
df_d = pd.DataFrame({'Employee_ID': [1, 2, 3], 'Salary': [60000, 75000, 80000]}).set_index('Employee_ID')

print("\ndf_c:")
display(df_c)
print("\ndf_d:")
display(df_d)

# Join df_c's index with df_d's index
merged_on_index_via_join = df_c.join(df_d)
print("\nJoin df_c and df_d on their indices:")
display(merged_on_index_via_join)

df_a:

    Value_A
K1       10
K2       20

df_b:

    Value_B
K1       30
K3       40

Left Join (df_a.join(df_b)):

    Value_A  Value_B
K1       10     30.0
K2       20      NaN

Inner Join (df_a.join(df_b, how='inner')):

    Value_A  Value_B
K1       10       30

df_c:

      Name   Dept
1    Alice     HR
2      Bob     IT
3  Charlie  Sales

df_d:

             Salary
Employee_ID
1             60000
2             75000
3             80000

Join df_c and df_d on their indices:

      Name   Dept  Salary
1    Alice     HR   60000
2      Bob     IT   75000
3  Charlie  Sales   80000

In [74]:
# Create two sample DataFrames
df_concat1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df_concat2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})

print("df_concat1:")
display(df_concat1)
print("\ndf_concat2:")
display(df_concat2)

# Concatenate along rows (default behavior, axis=0)
concat_rows = pd.concat([df_concat1, df_concat2])
print("\nConcatenated along rows:")
display(concat_rows)

# Concatenate along columns (axis=1)
concat_cols = pd.concat([df_concat1, df_concat2], axis=1)
print("\nConcatenated along columns:")
display(concat_cols)

# Concatenate with different columns, showing NaN for missing values
df_concat3 = pd.DataFrame({'C': ['C0', 'C1'], 'D': ['D0', 'D1']})
concat_diff_cols = pd.concat([df_concat1, df_concat3], axis=1)
print("\nConcatenated with different columns:")
display(concat_diff_cols)

df_concat1:

    A   B
0  A0  B0
1  A1  B1

df_concat2:

    A   B
0  A2  B2
1  A3  B3

Concatenated along rows:

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

Concatenated along columns:

    A   B   A   B
0  A0  B0  A2  B2
1  A1  B1  A3  B3

Concatenated with different columns:

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [75]:
# Create two sample DataFrames for merging
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
})
df2 = pd.DataFrame({
    'ID': [1, 3, 4, 5],
    'City': ['New York', 'Chicago', 'Houston', 'Miami'],
    'Salary': [70000, 80000, 90000, 60000]
})

print("df1:")
display(df1)
print("\ndf2:")
display(df2)

# Inner Merge (default)
inner_merge = pd.merge(df1, df2, on='ID', how='inner')
print("\nInner Merge (on ID):")
display(inner_merge)

# Left Merge
left_merge = pd.merge(df1, df2, on='ID', how='left')
print("\nLeft Merge (on ID):")
display(left_merge)

# Right Merge
right_merge = pd.merge(df1, df2, on='ID', how='right')
print("\nRight Merge (on ID):")
display(right_merge)

# Outer Merge
outer_merge = pd.merge(df1, df2, on='ID', how='outer')
print("\nOuter Merge (on ID):")
display(outer_merge)

df1:

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

df2:

   ID      City  Salary
0   1  New York   70000
1   3   Chicago   80000
2   4   Houston   90000
3   5     Miami   60000

Inner Merge (on ID):

   ID     Name  Age      City  Salary
0   1    Alice   25  New York   70000
1   3  Charlie   35   Chicago   80000
2   4    David   40   Houston   90000

Left Merge (on ID):

   ID     Name  Age      City   Salary
0   1    Alice   25  New York  70000.0
1   2      Bob   30       NaN      NaN
2   3  Charlie   35   Chicago  80000.0
3   4    David   40   Houston  90000.0

Right Merge (on ID):

   ID     Name   Age      City  Salary
0   1    Alice  25.0  New York   70000
1   3  Charlie  35.0   Chicago   80000
2   4    David  40.0   Houston   90000
3   5      NaN   NaN     Miami   60000

Outer Merge (on ID):

   ID     Name   Age      City   Salary
0   1    Alice  25.0  New York  70000.0
1   2      Bob  30.0       NaN      NaN
2   3  Charlie  35.0   Chicago  80000.0
3   4    David  40.0   Houston  90000.0
4   5      NaN   NaN     Miami  60000.0

In [76]:
# Create two DataFrames with common indices
df_a = pd.DataFrame({'Value_A': [10, 20]}, index=['K1', 'K2'])
df_b = pd.DataFrame({'Value_B': [30, 40]}, index=['K1', 'K3'])

print("df_a:")
display(df_a)
print("\ndf_b:")
display(df_b)

# Left Join (default for .join())
joined_df = df_a.join(df_b)
print("\nLeft Join (df_a.join(df_b)):")
display(joined_df)

# Inner Join with .join()
inner_joined_df = df_a.join(df_b, how='inner')
print("\nInner Join (df_a.join(df_b, how='inner')):")
display(inner_joined_df)

# Joining on a column rather than index
df_c = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Dept': ['HR', 'IT', 'Sales']}, index=[1, 2, 3])
df_d = pd.DataFrame({'Employee_ID': [1, 2, 3], 'Salary': [60000, 75000, 80000]}).set_index('Employee_ID')

print("\ndf_c:")
display(df_c)
print("\ndf_d:")
display(df_d)

# Join df_c's index with df_d's index
merged_on_index_via_join = df_c.join(df_d)
print("\nJoin df_c and df_d on their indices:")
display(merged_on_index_via_join)

df_a:

    Value_A
K1       10
K2       20

df_b:

    Value_B
K1       30
K3       40

Left Join (df_a.join(df_b)):

    Value_A  Value_B
K1       10     30.0
K2       20      NaN

Inner Join (df_a.join(df_b, how='inner')):

    Value_A  Value_B
K1       10       30

df_c:

      Name   Dept
1    Alice     HR
2      Bob     IT
3  Charlie  Sales

df_d:

             Salary
Employee_ID
1             60000
2             75000
3             80000

Join df_c and df_d on their indices:

      Name   Dept  Salary
1    Alice     HR   60000
2      Bob     IT   75000
3  Charlie  Sales   80000

## Module 10: Working with Time Series Data

Time series data is a crucial aspect of many data analyses, especially in finance, economics, and sensor data. Pandas provides robust tools for working with dates and times, making it easy to parse, manipulate, and analyze time-indexed data.

### 10.1 Date and Time Objects (`datetime`, `Timestamp`)

Pandas builds upon Python's built-in `datetime` module and extends it with its own `Timestamp` object, which is the type used for entries in a `DatetimeIndex`.

**Converting to Datetime:**

As seen in Module 6, `pd.to_datetime()` is the primary function for converting various date-like objects (strings, integers) into `datetime` objects.

In [77]:
# Using df_datetime_sample from Module 6 (ensure 'OrderDate' is datetime dtype)
print("DataFrame with 'OrderDate' as datetime dtype:")
display(df_datetime_sample.info())
display(df_datetime_sample.head())

DataFrame with 'OrderDate' as datetime dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      datetime64[ns]
 3   Amount     5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 292.0+ bytes

None

   OrderID Customer  OrderDate  Amount
0        1    Alice 2023-01-15  100.50
1        2      Bob 2023-01-16   75.25
2        3  Charlie 2023-02-01  200.00
3        4    David 2023-02-02   50.00
4        5      Eve 2023-03-10  120.75

### 10.2 DatetimeIndex and Resampling

Setting a `DatetimeIndex` is essential for leveraging Pandas' time series functionalities, such as easy slicing, resampling, and time-based calculations.

**Setting DatetimeIndex:**

In [78]:
# Set 'OrderDate' as the index
df_time_indexed = df_datetime_sample.set_index('OrderDate')
print("DataFrame with DatetimeIndex:")
display(df_time_indexed.info())
display(df_time_indexed.head())

DataFrame with DatetimeIndex:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2023-01-15 to 2023-03-10
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   5 non-null      int64
 1   Customer  5 non-null      object
 2   Amount    5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

None

            OrderID Customer  Amount
OrderDate
2023-01-15        1    Alice  100.50
2023-01-16        2      Bob   75.25
2023-02-01        3  Charlie  200.00
2023-02-02        4    David   50.00
2023-03-10        5      Eve  120.75

**Accessing Time-based Components:**

Once you have `datetime` objects or a `DatetimeIndex`, you can easily access various components like year, month, day, day of week, etc.

In [79]:
# Add new columns for time-based components
df_time_indexed['OrderYear'] = df_time_indexed.index.year
df_time_indexed['OrderMonth'] = df_time_indexed.index.month
df_time_indexed['DayOfWeek'] = df_time_indexed.index.day_name()

print("DataFrame with new time components:")
display(df_time_indexed.head())

DataFrame with new time components:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1     Sunday
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday
2023-03-10        5      Eve  120.75       2023           3     Friday

**Time-based Slicing:**

With a `DatetimeIndex`, you can easily slice data using dates or date ranges.

In [80]:
# Select data for a specific year
print("Orders in 2023:")
display(df_time_indexed.loc['2023'])

# Select data for a specific month
print("\nOrders in January 2023:")
display(df_time_indexed.loc['2023-01'])

# Select data for a date range
print("\nOrders between Jan 16 and Feb 02:")
display(df_time_indexed.loc['2023-01-16':'2023-02-02'])

Orders in 2023:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1     Sunday
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday
2023-03-10        5      Eve  120.75       2023           3     Friday

Orders in January 2023:

            OrderID Customer  Amount  OrderYear  OrderMonth DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1    Sunday
2023-01-16        2      Bob   75.25       2023           1    Monday

Orders between Jan 16 and Feb 02:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday

**Resampling Time Series Data:**

Resampling is the process of aggregating time series data into a lower or higher frequency. This is incredibly useful for analyzing trends over different time periods (e.g., daily to monthly, or hourly to daily).

Common resampling frequencies:
*   `'D'`: Day
*   `'W'`: Week
*   `'M'`: Month end
*   `'Q'`: Quarter end
*   `'A'`: Year end

In [81]:
# Resample to monthly frequency and calculate the sum of 'Amount'
monthly_sales = df_time_indexed['Amount'].resample('M').sum()
print("Monthly Sales (resampled and summed):")
display(monthly_sales)

Monthly Sales (resampled and summed):

/tmp/ipykernel_693/4237330864.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales = df_time_indexed['Amount'].resample('M').sum()

OrderDate
2023-01-31    175.75
2023-02-28    250.00
2023-03-31    120.75
Freq: ME, Name: Amount, dtype: float64

### 10.3 Time Deltas (`Timedelta`)

A `Timedelta` represents a duration or a difference between two `datetime` objects. They are useful for calculating durations, adding/subtracting time to/from dates.

In [82]:
from datetime import timedelta

# Create two Timestamp objects
date1 = pd.Timestamp('2023-01-15')
date2 = pd.Timestamp('2023-01-20')

# Calculate the difference (Timedelta)
time_diff = date2 - date1
print("Time difference (Timedelta):")
display(time_diff)

# Add a Timedelta to a date
future_date = date1 + pd.Timedelta(days=7)
print("\nDate plus 7 days:")
display(future_date)

# You can also create Timedeltas directly
days_ago = pd.Timestamp.today() - pd.Timedelta(weeks=2)
print("\nTwo weeks ago from today:")
display(days_ago)

Time difference (Timedelta):

Timedelta('5 days 00:00:00')

Date plus 7 days:

Timestamp('2023-01-22 00:00:00')

Two weeks ago from today:

Timestamp('2026-05-07 06:06:41.247904')

In [83]:
# Using df_datetime_sample from Module 6 (ensure 'OrderDate' is datetime dtype)
print("DataFrame with 'OrderDate' as datetime dtype:")
display(df_datetime_sample.info())
display(df_datetime_sample.head())

DataFrame with 'OrderDate' as datetime dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   Customer   5 non-null      object
 2   OrderDate  5 non-null      datetime64[ns]
 3   Amount     5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 292.0+ bytes

None

   OrderID Customer  OrderDate  Amount
0        1    Alice 2023-01-15  100.50
1        2      Bob 2023-01-16   75.25
2        3  Charlie 2023-02-01  200.00
3        4    David 2023-02-02   50.00
4        5      Eve 2023-03-10  120.75

In [84]:
# Set 'OrderDate' as the index
df_time_indexed = df_datetime_sample.set_index('OrderDate')
print("DataFrame with DatetimeIndex:")
display(df_time_indexed.info())
display(df_time_indexed.head())

DataFrame with DatetimeIndex:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2023-01-15 to 2023-03-10
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   5 non-null      int64
 1   Customer  5 non-null      object
 2   Amount    5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

None

            OrderID Customer  Amount
OrderDate
2023-01-15        1    Alice  100.50
2023-01-16        2      Bob   75.25
2023-02-01        3  Charlie  200.00
2023-02-02        4    David   50.00
2023-03-10        5      Eve  120.75

In [85]:
# Add new columns for time-based components
df_time_indexed['OrderYear'] = df_time_indexed.index.year
df_time_indexed['OrderMonth'] = df_time_indexed.index.month
df_time_indexed['DayOfWeek'] = df_time_indexed.index.day_name()

print("DataFrame with new time components:")
display(df_time_indexed.head())

DataFrame with new time components:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1     Sunday
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday
2023-03-10        5      Eve  120.75       2023           3     Friday

In [86]:
# Select data for a specific year
print("Orders in 2023:")
display(df_time_indexed.loc['2023'])

# Select data for a specific month
print("\nOrders in January 2023:")
display(df_time_indexed.loc['2023-01'])

# Select data for a date range
print("\nOrders between Jan 16 and Feb 02:")
display(df_time_indexed.loc['2023-01-16':'2023-02-02'])

Orders in 2023:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1     Sunday
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday
2023-03-10        5      Eve  120.75       2023           3     Friday

Orders in January 2023:

            OrderID Customer  Amount  OrderYear  OrderMonth DayOfWeek
OrderDate
2023-01-15        1    Alice  100.50       2023           1    Sunday
2023-01-16        2      Bob   75.25       2023           1    Monday

Orders between Jan 16 and Feb 02:

            OrderID Customer  Amount  OrderYear  OrderMonth  DayOfWeek
OrderDate
2023-01-16        2      Bob   75.25       2023           1     Monday
2023-02-01        3  Charlie  200.00       2023           2  Wednesday
2023-02-02        4    David   50.00       2023           2   Thursday

In [87]:
# Resample to monthly frequency and calculate the sum of 'Amount'
monthly_sales = df_time_indexed['Amount'].resample('M').sum()
print("Monthly Sales (resampled and summed):")
display(monthly_sales)

Monthly Sales (resampled and summed):

/tmp/ipykernel_693/4237330864.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales = df_time_indexed['Amount'].resample('M').sum()

OrderDate
2023-01-31    175.75
2023-02-28    250.00
2023-03-31    120.75
Freq: ME, Name: Amount, dtype: float64

In [88]:
from datetime import timedelta

# Create two Timestamp objects
date1 = pd.Timestamp('2023-01-15')
date2 = pd.Timestamp('2023-01-20')

# Calculate the difference (Timedelta)
time_diff = date2 - date1
print("Time difference (Timedelta):")
display(time_diff)

# Add a Timedelta to a date
future_date = date1 + pd.Timedelta(days=7)
print("\nDate plus 7 days:")
display(future_date)

# You can also create Timedeltas directly
days_ago = pd.Timestamp.today() - pd.Timedelta(weeks=2)
print("\nTwo weeks ago from today:")
display(days_ago)

Time difference (Timedelta):

Timedelta('5 days 00:00:00')

Date plus 7 days:

Timestamp('2023-01-22 00:00:00')

Two weeks ago from today:

Timestamp('2026-05-07 06:06:41.465907')

In [89]:
data_missing = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [10, 20, 30, np.nan, 50]
}
df_missing = pd.DataFrame(data_missing)
print("Original DataFrame with missing values:")
display(df_missing)

Original DataFrame with missing values:

     A    B     C
0  1.0  NaN  10.0
1  2.0  2.0  20.0
2  NaN  3.0  30.0
3  4.0  4.0   NaN
4  5.0  NaN  50.0